### ISSUE TITLE
missing run_glue.py

### ISSUE THREAD

**Issue by yqw0710** [princeton-nlp/MABEL#1]

**Comment by jacqueline-he** [comment]
Hi there,

`run_glue.py` is not a script that we provide; it's a file under the `transformers` repository [here](https://github.com/huggingface/transformers/blob/main/examples/pytorch/text-classification/run_glue.py). 

As per the instructions, you are supposed to clone the `transformers` repo, and run the script in the  `transformers/examples/pytorch/text-classification` folder.

**Comment by jacqueline-he** [comment]
Closing this for now—feel free to re-open if necessary!
