### ISSUE TITLE
NLI Benchmark Dataset Request

### ISSUE THREAD

**Issue by Elfsong** [princeton-nlp/MABEL#5]
Hi there, 

Could you share the processed version of [the Bias-NLI dataset](https://drive.google.com/file/d/1eC003yjOHjkp5-TGyVXW1emlV80qB7Yl/view?usp=sharing)? it needs to request access, I submitted my request already. Thank you!

Best regards,
Mingzhe

**Comment by jacqueline-he** [comment]
Hi,

Sorry for missing your request--the processed NLI dataset can be accessed [here](https://drive.google.com/file/d/1cY5PZgUVJcsWgtOODGWmPz8qxnHoPc8t/view?usp=sharing). I believe the former Drive link led to a version of the dataset that was not shuffled properly, which affects the distributions in the train / val / test partitions. 

Alternatively, you can re-generate the dataset by following the instructions from the original source [here](https://github.com/sunipa/On-Measuring-and-Mitigating-Biased-Inferences-of-Word-Embeddings/blob/fba4c8723a687f4c1de7c6ff4744ad84b100f170/word_lists/README.md). You could do some light pre-processing to get the columns formatted as [`premise`, `hypothesis`, `label`], in which the `label` value should always be `entailment` (or 1), and then shuffle all the examples.

**Comment by Elfsong** [comment]
Really appreciate! Thank you for making this solid work.
